<?php

namespace NT\PlatformBundle\Repository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findPriceByCommand(){
//    $qb = $this->_em->createQueryBuilder();
//    $qb
//    ->select('SUM(ta.price) AS totalprice, t.command')
//    ->from('NTPlatformBundle:Tarif', 'ta')
//    ->innerJoin('t.tickets', 't')
//    ->addSelect('t')
//    ->groupBy('t.command');
//    return $qb
//    ->getQuery()
//    ->getResult();
//    }
}
