<?php

namespace NT\PlatformBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

  public function maxDixBilletsDate()
  {
    $qb = $this->_em->createQueryBuilder();
    $qb
    ->select('t.visitDay AS day, COUNT(t.id) AS amount')
    ->from('NTPlatformBundle:Ticket', 't')
    ->groupBy('day');
    return $qb
    ->getQuery()
    ->getResult();
  }
    
  public function TwoHours()
  {
    $qb = $this->_em->createQueryBuilder();
    $qb
    ->select('t.visitDay AS day')
    ->from('NTPlatformBundle:Ticket', 't')
    ->where('day = :today')
//    ->andWhere('hour') = 14
//    ->andWhere('hour < :now')
    ->setParameter('today', new \DateTime('Europe/Paris'));
//    ->setParameter('now', print date('H'));
    return $qb
    ->getQuery()
    ->getResult();
  }
   
//  public function TotalPrice()
//  {
//    $qb = $this->_em->createQueryBuilder();
//    $qb
//    ->select('t.command, SUM(t.price)') 
//    ->from('NTPlatformBundle:Ticket', 't')
//    ->rightJoin('tarif ta ON t.tarif_id = ta.id') 
//    ->groupBy('t.command');
//    return $qb
//    ->getQuery()
//    ->getResult();
//  }
}
